server:
  port: 8099

spring:
  application:
    name: microservice
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
