server:
  port: 8099
spring:
  application:
    name:personService
main:
  allow-bean-definition-overriding: true
data:
  mongodb:
    #182.28.0.11
    host: mongo_DB
    port: 27017
    database: tutorialsservice_db
