version: '3.8'

networks:
  mired2:
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

services:
  db:
    image: bitnami/mongodb:latest
    container_name: mongoAgenda_DB
    networks:
      mired2:
        ipv4_address: 192.168.100.10
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: agenda-db
    restart: always

  app-agenda:
    build: .
    container_name: agenda
    networks:
      mired2:
        ipv4_address: 192.168.100.11
    ports:
      - "8099:8099"
    depends_on:
      - db
    environment:
      SPRING_DATA_MONGODB_HOST: mongoAgenda_DB
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: agenda-db
    restart: always
